### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by EdisionWew** [1e100/vovnet_v2#1]
Hello, the author, the repo is great, but I found the checkpoints of this repo are invlid, when I use them as a backbone. Could you update them? thanks.

**Comment by 1e100** [comment]
Hi @EdisionWew, I think I updated the code, but neglected to update the checkpoints. Which configuration do you need? I'll retrain it first and post a new checkpoint in a few days when that's done.

**Comment by 1e100** [comment]
Actually, hold on. I have just tried loading the checkpoints and they seem to work fine. Do you have `git lfs` installed? If not, you need to install and initialize it, then clone the repo again. See here for more details: https://git-lfs.github.com/

**Comment by 1e100** [comment]
The files under `checkpoints` will have the following sizes:
```
12M Sep 16 01:00 vovnet19-72.03-top1.pt
15M Sep 16 01:00 vovnet27-73.07-top1.pt
101M Sep 16 01:00 vovnet39-78.82-top1.pt
163M Sep 16 01:00 vovnet57-79.63-top1.pt
```

**Comment by EdisionWew** [comment]
Hi, thinks so much, it caused that git lfs was not installed. A nice author.
